---
title: "ENV S 193DS Final"
format: 
  html:
    toc: TRUE 
---

```{r setup}
library(tidyverse)
# load your data

```

# Problem 1. Research writing 

## a. Transparent statistical methods 

In part 1 my co-worker used a correlation test to assess the linear relationship between the distance from the headwater (km) and the annual nitrogen load (kg year⁻¹). In their statement they use the term "correlation" and provide a p-value. In part 2 they used an analysis of variance (ANOVA) to compare the mean nitrogen load across more than one course category (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands). ANOVA is usually sued to test for differences in means cross more than two groups, so we can infer that this is what they likely used.

## b. More information needed 
One test that they could do to provide more context to the results is look into the effect size. Only including a p-value tells us that the difference likely exists but not how large or significant that difference is. By including an effect size would help to assign a quantity for how much of the variation in nitrogen load can be explained by the type of source its coming fro, which is critical for making informed management decisions. Another test that could be done is Tukey's HSD or post-doc pairwise comparison as the results from the ANOVA only tell that some group means differ but doesn't say which ones are different from each other. Doing a post-hoc test would identify whether, for example, nitrogen load from waste water treatment differed significantly than that from fertilizer. 

## c. Suggestions for rewriting
Suggested rewrite for part 1:

As the nitrogen load tends to increase or decrease with distance from the headwater, this suggests a spatial trend in nutrient accumulation or dilution in the waters of the San Joaquin River Delta. This relationship is supported by a correlation analysis (Pearson’s correlation test: r = correlation coefficient, p = 0.03, α = significance level).

Suggested rewrite for part 2:

The average nitrogen load was different among land use and nitrogen source categories, which suggests that certain types of sources contribute more to nitrogen input in the San Joaquin River Delta. This was supported by an analysis of variance (F-statistic = [F-value], degrees of freedom = [df1, df2], p = 0.02, α = [significance level]). Howwver, the inclusion of post-hoc comparisons and effect size measures are needed to identify which sources differ and the magnitude of their contributions.

# Problem 2. Data visualization 

## a. Cleaning and summarizing

## b. Visualize the data 


# Problem 3. Data analysis 

## a. Response variable 

## b. Purpose of study

## c. Difference in “seasons”

## d. Table of models 

## e. Run the models 

## f. Check the diagnostics

## g. Select the best model 

## h. Visualize the model predictions 

## i. Write a caption for your figure. 

## j. Calculate model predictions 

## k. Interpret your results 

# Probelm 4. Affective and exploratory visualizations

## a. Comparing visualizations

## b. Sharing your affective visualization 

[Attendance to workshop 10 during Week 10 :)]